### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [goldsborough/lru-cache#9]
Would you like to [replace any double quotes](https://github.com/goldsborough/lru-cache/blob/90b067e7ec2ce28439cab84aeea9e3c98bcb7845/include/lru/lru.hpp#L25 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by goldsborough** [comment]
Interesting, I figure that *technically* it would make more sense for a library like this one to use angle brackets since the files will most likely not be in the same directory. In practice I've never found it to be an issue and I like the visual distinction of `<standard>` vs. `"mine.h"`. What's your opinion?

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "Draft for the C++ standard specification") in the standard specification for the programming language "C++".

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid "a duplicated file search" here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Description for include syntax") for header files of your software?

**Comment by goldsborough** [comment]
Replaced #include "..." with #include <...>

**Comment by elfring** [comment]
Which commits will contain corresponding changes?

**Comment by goldsborough** [comment]
Forgot to push [the commit](https://github.com/goldsborough/lru-cache/commit/505223185b00dadfb3674e3ae2e20c44c9a7c5e9) back then. Thanks.

**Comment by elfring** [comment]
Thanks for [your source code adjustment](https://github.com/goldsborough/lru-cache/commit/505223185b00dadfb3674e3ae2e20c44c9a7c5e9 "Changed include style").
